#
# Copyright Â© 2017-2018 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: Service
apiVersion: v1
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  type: LoadBalancer
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 9191
      targetPort: 9191
      name: nifi
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  serviceName: nifi
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:1.6.0
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9091
          name: nifi
        volumeMounts:
        - mountPath: /opt/nifi/nifi-1.4.0/flowfile_repository
          name: nifi-flowfile-repo-dir
        - mountPath: /opt/nifi/nifi-1.4.0/database_repository
          name: nifi-db-repo-dir
        - mountPath: /opt/nifi/nifi-1.4.0/content_repository
          name: nifi-content-repo-dir
        - mountPath: /opt/nifi/nifi-1.4.0/provenance_repository
          name: nifi-provenance-repo-dir
        - mountPath: /opt/nifi/nifi-1.4.0/logs
          name: nifi-log-dir
  volumeClaimTemplates:
  - metadata:
      name: nifi-flowfile-repo-dir 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gold
  - metadata:
      name: nifi-db-repo-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gold
  - metadata:
      name: nifi-content-repo-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gold
  - metadata:
      name: nifi-provenance-repo-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gold
  - metadata:
      name: nifi-log-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gold
