apiVersion: v1
kind: Pod
metadata:
  name: cassandra-setup
spec:
  containers:
  - name: cassandra-setup
    imagePullPolicy: Always
    image: tempus/cassandra-setup:1.4.0
    env:
    - name: ADD_DEMO_DATA
      value: "true"
    - name : CASSANDRA_HOST
      value: "cassandra-headless"
    - name : CASSANDRA_PORT
      value: "9042"
    - name : DATABASE_TYPE
      value: "cassandra"
    - name : CASSANDRA_URL
      value: "cassandra-headless:9042"
    command:
    - sh
    - -c
    - /install.sh
  restartPolicy: Never